# Generated by Django 4.2 on 2023-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, default='Your answer is wrong.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer1',
            field=models.TextField(blank=True, default='Bad answer 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer2',
            field=models.TextField(blank=True, default='Bad answer 2'),
        ),
    ]
